#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
#
# gendiagnostics.py — generate tscaly/DiagnosticCodes.scaly from the pinned
# reference's diagnostic message table.
#
# The yardstick compares a diagnostic's CODE and SPAN, never its text (see
# TESTPLAN.md — the message lives in a 2000-entry table this port has no reason
# to carry). So what the port needs from `internal/diagnostics` is one integer
# per message, and typing those by hand would be 60-odd magic numbers whose only
# check is a reader's eye.
#
# ★ WHICH messages: exactly the ones the reference's SCANNER and PARSER
# reference, deduped — `grep -o 'diagnostics\.[A-Za-z_0-9]*'` over scanner.go and
# parser.go. That rule is mechanical and it is the reason this generator does not
# emit all ~2400 codes: a table nothing reads is a table nobody checks, and the
# two files named here are precisely the port's surface. A message that a later
# slice needs (the checker's) will be picked up by widening the SOURCES list,
# which is a one-line edit with a stated reason.
#
# ★ The emitted NAME is the reference's own Go identifier with a `Diag` prefix,
# unaltered — mixed case, underscores and all. It reads oddly in Scaly and that
# is the point: a site in our scanner spells the same name as the site in the
# reference's, so the two can be diffed by eye and by grep. Renaming them into
# house style would break the only check there is.
#
# Usage (from the repo root, submodule initialized):
#   packages/tscaly/tools/gendiagnostics.py
#
# The output is committed. With the submodule absent the committed file stays
# valid and this script simply cannot run — same arrangement as genkind.py.

import os
import re
import sys

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
SUB = os.path.join(REPO, "packages/tscaly/_submodules/typescript-go")
TABLE = os.path.join(SUB, "internal/diagnostics/diagnostics_generated.go")
SOURCES = [
    os.path.join(SUB, "internal/scanner/scanner.go"),
    os.path.join(SUB, "internal/parser/parser.go"),
]
DST = os.path.join(REPO, "packages/tscaly/0.1.0/tscaly/DiagnosticCodes.scaly")

# var X_0_expected = &Message{code: 1005, category: CategoryError, key: "...", text: "..."}
ENTRY = re.compile(r'^var (\w+) = &Message\{code: (\d+), category: Category(\w+),')
USE = re.compile(r"\bdiagnostics\.([A-Za-z_][A-Za-z_0-9]*)\b")


def main():
    if not os.path.exists(TABLE):
        sys.exit(
            "the reference submodule is not initialized — nothing to generate from:\n"
            "  git submodule update --init packages/tscaly/_submodules/typescript-go"
        )

    codes = {}
    categories = {}
    with open(TABLE, encoding="utf-8") as f:
        for line in f:
            m = ENTRY.match(line)
            if m:
                codes[m.group(1)] = int(m.group(2))
                categories[m.group(1)] = m.group(3)

    used = set()
    for src in SOURCES:
        with open(src, encoding="utf-8") as f:
            used |= set(USE.findall(f.read()))

    # `diagnostics.Message` is the TYPE, not a message; it appears in every
    # signature. Anything else that does not resolve is a real problem with this
    # scrape and is reported rather than skipped — the trap the root CLAUDE.md
    # records for the ABI audit, where 82 wrong result types hid behind one
    # silently unparsable type name.
    used.discard("Message")
    missing = sorted(n for n in used if n not in codes)
    if missing:
        sys.exit(
            "these names are referenced by the scanner or parser but are not in the\n"
            "message table — the scrape is wrong, not the reference:\n  "
            + "\n  ".join(missing)
        )

    names = sorted(used, key=lambda n: (codes[n], n))
    # Align to a readable column rather than to the LONGEST name: one reference
    # message identifier is 154 characters, and padding every line out to it
    # turns the file into whitespace. A name past the column simply gets one
    # space, which the formatter corpus check accepts either way.
    width = min(max(len("Diag" + n) for n in names) + 1, 76)

    out = []
    out.append("; SPDX-License-Identifier: Apache-2.0")
    out.append(";")
    out.append("; DiagnosticCodes — the TS error numbers, ported from the reference's")
    out.append("; internal/diagnostics/diagnostics_generated.go.")
    out.append(";")
    out.append("; GENERATED by packages/tscaly/tools/gendiagnostics.py. Do not edit; edit the")
    out.append("; generator. Regenerate after a submodule pin bump.")
    out.append(";")
    out.append("; ONE INTEGER PER MESSAGE, and no text. The yardstick compares a diagnostic's")
    out.append("; code and span; the message string lives in a table this port has no reason to")
    out.append("; carry, and TESTPLAN.md says so where it lists what the dump format does not")
    out.append("; show — a wrong message with a right code passes here.")
    out.append(";")
    out.append("; The set is exactly the messages the reference's scanner.go and parser.go")
    out.append("; reference, deduped. The NAMES are the reference's own Go identifiers with a")
    out.append("; `Diag` prefix and nothing else changed, so a site in our scanner spells the")
    out.append("; same name as the site in theirs and the two can be diffed by grep.")
    out.append(";")
    out.append("; Sorted by CODE rather than by name, because that is the order a failing")
    out.append("; diff prints them in.")
    out.append("")
    for n in names:
        # ★ A name past the alignment column still needs its separating space —
        # ljust does nothing there, and `…inclusive:int 1198` is a different token
        # sequence from `…inclusive: int 1198`. Caught by a grep for the code that
        # found 124 of the 125 and reported the 125th as absent.
        label = ("Diag" + n + ":").ljust(width)
        if not label.endswith(" "):
            label += " "
        out.append(
            "define {}int {}{}".format(
                label,
                codes[n],
                "" if categories[n] == "Error" else "   ; " + categories[n],
            )
        )
    out.append("")

    with open(DST, "w", encoding="utf-8") as f:
        f.write("\n".join(out))

    print(
        "wrote {} ({} codes, from {} messages in the table)".format(
            os.path.relpath(DST, REPO), len(names), len(codes)
        )
    )


if __name__ == "__main__":
    main()
