#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
#
# genfeaturemap.py — generate tscaly/FeatureMap.scaly from the reference's
# `getFeatureMap` in internal/checker/utilities.go.
#
# ★★★ WHY IT IS GENERATED. The table is 260 reference lines of pure data — a
# TYPE name, a lib name and the property names that lib adds to that type — and
# its ONLY reader is getSuggestedLibForNonExistentProperty, which turns a missing
# property into TS2550 (*change your target library*) instead of TS2339. So a
# transcription slip is not a compile error and not a wrong VALUE either: it is
# the wrong DIAGNOSTIC CODE on one property of one type, several hundred units
# away from the table, and only the corpus would ever see it.
#
# ★★ THE OUTPUT IS A FUNCTION AND NOT A TABLE, because of how Scaly treats
# const array globals: an `[N x T]` value cannot be handed to a
# pointer parameter, and a table of STRINGS has no such spelling at all. The
# lookup is a chain of byte comparisons — the same shape Keywords.scaly uses —
# and it answers the lib name's bytes through two out-parameters.
#
# Usage (from the repo root, submodule initialized):
#   packages/tscaly/tools/genfeaturemap.py
#
# The output is committed; with the submodule absent the committed file stays
# valid and this script simply cannot run.
import io, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
SRC = os.path.join(ROOT, "packages/tscaly/_submodules/typescript-go/internal/checker/utilities.go")
OUT = os.path.join(ROOT, "packages/tscaly/0.1.2/tscaly/FeatureMap.scaly")

if not os.path.exists(SRC):
    sys.stderr.write("submodule absent — nothing to generate from.\n")
    sys.exit(2)

text = io.open(SRC, encoding="utf-8").read()
start = text.index("var getFeatureMap = sync.OnceValue(")
end = text.index("\n})\n", start)
body = text[start:end]

# The map is `"<Type>": { {lib: "<lib>", props: []string{"a", "b"}}, … }`.
entries = []          # (type name, lib, [props])
cur_type = None
i = 0
lines = body.split("\n")
pending_lib = None
pending_props = []
in_props = False
for raw in lines[2:]:
    line = raw.strip()
    m = re.match(r'^"([^"]+)":\s*\{$', line)
    if m:
        cur_type = m.group(1)
        continue
    if line == "},":
        if in_props:
            in_props = False
            entries.append((cur_type, pending_lib, pending_props))
            pending_lib, pending_props = None, []
        else:
            cur_type = None
        continue
    m = re.match(r'^\{lib:\s*"([^"]+)",\s*props:\s*\[\]string\{(.*)\}\},$', line)
    if m:
        props = re.findall(r'"([^"]*)"', m.group(2))
        entries.append((cur_type, m.group(1), props))
        continue
    m = re.match(r'^\{lib:\s*"([^"]+)",\s*props:\s*\[\]string\{$', line)
    if m:
        pending_lib, pending_props, in_props = m.group(1), [], True
        continue
    if in_props:
        pending_props.extend(re.findall(r'"([^"]*)"', line))
        # a multi-line prop list closes with `}},` on its own line
        if line.endswith("}},"):
            in_props = False
            entries.append((cur_type, pending_lib, pending_props))
            pending_lib, pending_props = None, []
        continue

assert entries, "parsed nothing — the reference's shape moved"

def scaly_str(s):
    return '"%s"' % s.replace("\\", "\\\\").replace('"', '\\"')

o = io.StringIO()
o.write("; SPDX-License-Identifier: Apache-2.0\n;\n")
o.write("; FeatureMap — getSuggestedLibForNonExistentProperty's table, ported from the\n")
o.write("; reference's `getFeatureMap` in internal/checker/utilities.go.\n;\n")
o.write("; GENERATED by packages/tscaly/tools/genfeaturemap.py. Do not edit; edit the\n")
o.write("; generator. Regenerate after a submodule pin bump.\n;\n")
o.write("; ★★★ THE ORDER IS LOAD-BEARING. The reference walks a type's entries in\n")
o.write("; declaration order and answers the FIRST lib whose prop list contains the\n")
o.write("; missing name, so two libs that both add a name would answer differently if\n")
o.write("; the rows were sorted.\n")
o.write(";\n; %d rows over %d types.\n\n" % (len(entries), len(set(e[0] for e in entries))))
o.write("define FeatureMap\n{\n")
o.write("    ; Checker.name_bytes_are, written out here rather than called.\n")
o.write("    ;\n")
o.write("    ; \u2605\u2605 THIS MODULE IS DECLARED BEFORE `checker` \u2014 it is a constant table and\n")
o.write("    ; the table modules go first, on the module-ORDER rule the package root\n")
o.write("    ; states \u2014 so calling into the checker from here would be a call into a\n")
o.write("    ; module declared LATER. Twelve lines is the price of not testing that.\n")
o.write("    function bytes_are(name: Slice[char], t: Slice[char]) returns bool\n")
o.write("    {\n")
o.write("        if name.data = null\n")
o.write("            return false\n")
o.write("        if name.length <> t.length\n")
o.write("            return false\n")
o.write("        var i: size_t 0\n")
o.write("        while i < name.length\n")
o.write("        {\n")
o.write("            if name[i] <> t[i]\n")
o.write("                return false\n")
o.write("            i := i + 1\n")
o.write("        }\n")
o.write("        true\n")
o.write("    }\n\n")
o.write("    ; getSuggestedLibForNonExistentProperty's inner two loops: the lib that adds the\n")
o.write("    ; property to the type, or empty\n")
o.write("    function suggested_lib(type_name: Slice[char], prop: Slice[char]) returns Slice[char]\n")
o.write("    {\n")
by_type = {}
for t, lib, props in entries:
    by_type.setdefault(t, []).append((lib, props))
for t in by_type:
    o.write("        if FeatureMap.bytes_are(type_name, %s)\n" % scaly_str(t))
    o.write("        {\n")
    for lib, props in by_type[t]:
        for p in props:
            o.write("            if FeatureMap.bytes_are(prop, %s)\n" % scaly_str(p))
            o.write("                return %s\n" % scaly_str(lib))
        if not props:
            o.write("            ; `%s` adds no property names to this type \u2014 an empty row upstream.\n" % lib)
    o.write("            return \"\"\n")
    o.write("        }\n")
o.write("        \"\"\n")
o.write("    }\n\n")
o.write("    function has_suggested_lib(type_name: Slice[char], prop: Slice[char]) returns bool\n")
o.write("        FeatureMap.suggested_lib(type_name, prop).length > 0\n\n")
o.write("    ; getSuggestedLibForNonExistentName: the FIRST entry's lib of a type the map knows, or empty\n")
o.write("    function first_lib(type_name: Slice[char]) returns Slice[char]\n")
o.write("    {\n")
for t in by_type:
    o.write("        if FeatureMap.bytes_are(type_name, %s)\n" % scaly_str(t))
    o.write("            return %s\n" % scaly_str(by_type[t][0][0]))
o.write("        \"\"\n")
o.write("    }\n")
o.write("}\n")

io.open(OUT, "w", encoding="utf-8").write(o.getvalue())
sys.stderr.write("wrote %s (%d rows, %d types)\n" % (OUT, len(entries), len(by_type)))
