#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""genjsxentities.py — writes packages/tscaly/0.1.2/tscaly/JsxEntities.scaly from the
reference's entity table (transformers/jsxtransforms/jsx.go, `var entities = map[string]rune`),
as a generated if-chain (§3.23: a lookup table the reference builds as data becomes a
GENERATED function). Idempotent; tools/gencheck.sh runs it."""
import os, re, sys
HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.dirname(HERE)
SRC = os.path.join(PKG, "_submodules", "typescript-go", "internal", "transformers", "jsxtransforms", "jsx.go")
OUT = os.path.join(PKG, "0.1.2", "tscaly", "JsxEntities.scaly")
text = open(SRC, encoding="utf-8").read()
block = text[text.index("var entities = map[string]rune{"):]
block = block[:block.index("\n}")]
entries = re.findall(r'"([A-Za-z0-9]+)":\s*0x([0-9A-Fa-f]+),', block)
assert len(entries) > 200, len(entries)
lines = []
lines.append("; SPDX-License-Identifier: Apache-2.0")
lines.append("; JsxEntities — GENERATED by packages/tscaly/tools/genjsxentities.py from the")
lines.append("; reference's transformers/jsxtransforms/jsx.go entity table (`&nbsp;` and its")
lines.append("; kin). Edit the GENERATOR, never this file; tools/gencheck.sh compares.")
lines.append(";")
lines.append("; A structure with a field rather than a bare namespace: a field-less define's")
lines.append("; functions are FREE and mangle without its name.")
lines.append("define JsxEntities (unused: int)")
lines.append("{")
lines.append("    ; the code point of a named entity, or -1 when the name is not one")
lines.append("    function decode(name: Slice[char]) returns int")
lines.append("    {")
for name, hexv in entries:
    lines.append('        if name.equals("%s")' % name)
    lines.append("            return %d" % int(hexv, 16))
lines.append("        0 - 1")
lines.append("    }")
lines.append("}")
lines.append("")
new = "\n".join(lines)
old = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else None
if old != new:
    open(OUT, "w", encoding="utf-8").write(new)
print("%d entities -> %s" % (len(entries), os.path.relpath(OUT)))
