#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
#
# genkind.py — generate tscaly/Kind.scaly from the pinned reference's Kind enum.
#
# Upstream generates internal/ast/kind_generated.go from _scripts/generate-go-ast.ts
# ("Code generated ... DO NOT EDIT"), so hand-transcribing its 386 entries would
# make a generated file the input of a manual step and guarantee drift at the
# first pin bump. This reads the Go enum and emits the Scaly one.
#
# ★ THE ORDER IS LOAD-BEARING, which is the whole reason this is mechanical
# rather than a judgement call: 25 range markers (KindFirstKeyword/KindLastKeyword,
# KindFirstPunctuation/KindLastPunctuation, ...) are defined as the value of some
# other member, and every predicate over them is a `>=` and `<=` against a
# CONTIGUOUS run. Insert, drop or reorder one entry and those predicates keep
# compiling and start answering wrong — the same failure mode as
# dazzle's `Insn union` declaration order.
#
# Usage (from the repo root, submodule initialized):
#   packages/tscaly/tools/genkind.py
#
# The output is committed. With the submodule absent the committed file stays
# valid and this script simply cannot run — same arrangement as the openjade
# codegen in ./mkp.

import os
import re
import sys

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
SRC = os.path.join(
    REPO,
    "packages/tscaly/_submodules/typescript-go/internal/ast/kind_generated.go",
)
DST = os.path.join(REPO, "packages/tscaly/0.1.1/tscaly/Kind.scaly")

MEMBER = re.compile(r"^\tKind(\w+)(?:\s*//\s*(.*))?$")
ALIAS = re.compile(r"^\tKind(\w+)\s*=\s*Kind(\w+)\s*$")
SECTION = re.compile(r"^\t//\s*(.*)$")


def parse(path):
    """Return (entries, aliases).

    entries: list of (name, value, trailing_comment, section_comment_before)
    aliases: list of (name, target_name)
    """
    with open(path, encoding="utf-8") as f:
        lines = f.read().splitlines()

    try:
        start = lines.index("const (")
    except ValueError:
        sys.exit("genkind: no `const (` block found in %s" % path)

    entries = []
    aliases = []
    value = 0
    pending_section = None
    seen_count = False

    for line in lines[start + 1 :]:
        if line == ")":
            break

        m = SECTION.match(line)
        if m:
            pending_section = m.group(1)
            continue

        m = ALIAS.match(line)
        if m:
            aliases.append((m.group(1), m.group(2)))
            pending_section = None
            continue

        m = MEMBER.match(line)
        if m:
            name, comment = m.group(1), m.group(2)
            # The first member carries the `Kind = iota` that starts the run.
            if name.endswith(" Kind = iota"):
                name = name[: -len(" Kind = iota")]
            entries.append((name, value, comment, pending_section))
            pending_section = None
            if name == "Count":
                seen_count = True
            else:
                value += 1
            continue

        # `KindUnknown Kind = iota` — the run's first member, with its type.
        m = re.match(r"^\tKind(\w+)\s+Kind\s*=\s*iota\s*$", line)
        if m:
            entries.append((m.group(1), value, None, pending_section))
            pending_section = None
            value += 1
            continue

    if not seen_count:
        sys.exit("genkind: KindCount not found — the enum shape changed")

    return entries, aliases


def emit(entries, aliases):
    by_name = {name: value for name, value, _, _ in entries}
    width = max(len("Kind" + name) for name, _, _, _ in entries)

    out = []
    out.append("; SPDX-License-Identifier: Apache-2.0")
    out.append(";")
    out.append("; Kind — the syntax-kind tag, ported from the reference's")
    out.append("; internal/ast/kind_generated.go.")
    out.append(";")
    out.append("; GENERATED by packages/tscaly/tools/genkind.py. Do not edit; edit the")
    out.append("; generator. Regenerate after a submodule pin bump.")
    out.append(";")
    out.append("; ★ THE DECLARATION ORDER IS LOAD-BEARING. The range markers at the foot of")
    out.append("; this file are values of other members, and every predicate over them is a")
    out.append("; >= / <= against a CONTIGUOUS run — is_keyword is KindFirstKeyword <= k <=")
    out.append("; KindLastKeyword and nothing more. Reorder an entry and those predicates")
    out.append("; keep compiling while answering wrong.")
    out.append(";")
    out.append("; Upstream declares this as int16. Here it is int (i64): the width only")
    out.append("; starts to matter when Node carries the tag by value, which is the parser")
    out.append("; stage, not the scanner's. Revisit it there rather than guessing now.")
    out.append("")

    for name, value, comment, section in entries:
        if section:
            out.append("")
            out.append("; %s" % section)
        line = "define %-*s int %d" % (width + 2, "Kind" + name + ":", value)
        if comment:
            line += "  ; %s" % comment
        out.append(line.rstrip())

    out.append("")
    out.append("; Range markers — aliases for the members that bound each contiguous run.")
    awidth = max(len("Kind" + n) for n, _ in aliases)
    # An alias may name another alias (KindLastToken = KindLastKeyword), so
    # resolve as we go rather than against the members alone. Aliases are emitted
    # in source order, and Scaly folds only literal initializers here anyway, so
    # each one is written out as its resolved number.
    resolved = dict(by_name)
    for name, target in aliases:
        if target not in resolved:
            sys.exit(
                "genkind: alias Kind%s names Kind%s, which is neither a member nor an "
                "earlier alias — the enum shape changed" % (name, target)
            )
        value = resolved[target]
        resolved[name] = value
        out.append(
            "define %-*s int %d  ; = Kind%s"
            % (awidth + 2, "Kind" + name + ":", value, target)
        )

    out.append("")
    return "\n".join(out)


def main():
    if not os.path.exists(SRC):
        sys.exit(
            "genkind: reference not found at\n  %s\n"
            "Initialize the submodule:\n"
            "  git submodule update --init packages/tscaly/_submodules/typescript-go"
            % SRC
        )

    entries, aliases = parse(SRC)
    text = emit(entries, aliases)

    os.makedirs(os.path.dirname(DST), exist_ok=True)
    with open(DST, "w", encoding="utf-8") as f:
        f.write(text)

    print(
        "genkind: %d kinds + %d range markers -> %s"
        % (len(entries) - 1, len(aliases), os.path.relpath(DST, REPO))
    )


if __name__ == "__main__":
    main()
