#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
#
# genkeywords.py — generate tscaly/Keywords.scaly from the reference's
# textToKeyword map (internal/scanner/scanner.go).
#
# Generated for the same reason as Kind.scaly: 85 entries transcribed by hand are
# 85 chances to map a keyword to the wrong Kind, and a wrong entry produces a
# perfectly well-formed token stream that simply disagrees with the reference —
# the failure mode this port is organized against.
#
# Shape of the output. The reference does a map lookup guarded by
# `len(str) >= 2 && len(str) <= 12 && str[0] >= 'a' && str[0] <= 'z'`
# (GetIdentifierToken). Every keyword satisfies that guard, so it is a pure
# optimization and is ported as one. Behind the guard this emits a dispatch on
# LENGTH first and then a byte-wise comparison per candidate — a linear scan
# within one length bucket, at most 15 candidates deep.
#
# That is deliberately NOT a hash map: HashMap[String, int] would mean
# constructing a String per identifier scanned, and
# cross-package generic-init resolution is a known compiler defect. A flat
# comparison over the raw buffer has neither problem. If this ever shows up in a
# profile, replace it with a perfect hash over the same generated table — but
# measure first; the reference's own map lookup is guarded exactly this way.

import os
import re
import sys

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
SRC = os.path.join(
    REPO,
    "packages/tscaly/_submodules/typescript-go/internal/scanner/scanner.go",
)
DST = os.path.join(REPO, "packages/tscaly/0.1.2/tscaly/Keywords.scaly")

ENTRY = re.compile(r'^\t"([a-z]+)":\s*ast\.(Kind\w+),\s*$')


def parse(path):
    with open(path, encoding="utf-8") as f:
        lines = f.read().splitlines()

    try:
        start = lines.index("var textToKeyword = map[string]ast.Kind{")
    except ValueError:
        sys.exit("genkeywords: textToKeyword map not found in %s" % path)

    out = []
    for line in lines[start + 1 :]:
        if line == "}":
            break
        m = ENTRY.match(line)
        if not m:
            sys.exit("genkeywords: unparsable entry, shape changed: %r" % line)
        out.append((m.group(1), m.group(2)))

    if not out:
        sys.exit("genkeywords: the map parsed as empty")
    return out


def emit(entries):
    by_len = {}
    for text, kind in entries:
        by_len.setdefault(len(text), []).append((text, kind))

    lo = min(by_len)
    hi = max(by_len)

    out = []
    out.append("; SPDX-License-Identifier: Apache-2.0")
    out.append(";")
    out.append("; Keywords — the reference's textToKeyword map plus its")
    out.append("; GetIdentifierToken guard (internal/scanner/scanner.go).")
    out.append(";")
    out.append("; GENERATED by packages/tscaly/tools/genkeywords.py. Do not edit; edit the")
    out.append("; generator. Regenerate after a submodule pin bump.")
    out.append(";")
    out.append("; The reference guards its map lookup with")
    out.append(";   len(str) >= 2 && len(str) <= 12 && str[0] >= 'a' && str[0] <= 'z'")
    out.append("; and every keyword satisfies it, so the guard is an optimization, not a")
    out.append("; rule — it is ported as one. Behind it: dispatch on length, then compare")
    out.append("; bytes. No String is constructed, so scanning an identifier allocates")
    out.append("; nothing at all.")
    out.append(";")
    out.append("; ★ The bounds below are DERIVED from the table (%d..%d); the reference writes" % (lo, hi))
    out.append("; the upper one as a literal 12. That is not a behavioural deviation — the")
    out.append("; guard's only requirement is that it exclude no keyword, and both bounds")
    out.append("; satisfy it, so the two agree on every input. Deriving it makes that")
    out.append("; property true by construction instead of true by coincidence: a pin bump")
    out.append("; that introduces a longer keyword regenerates a correct bound, where a")
    out.append("; transcribed literal would silently start rejecting it.")
    out.append("")
    out.append("use scaly.containers.String")
    out.append("")

    # byte-comparison helper
    #
    # ★★★THE SLICE FORM BELONGS IN THE GENERATOR, NOT ONLY IN THE FILE.
    # `word` was `(pointer[const_char], int)` and was converted to a Slice
    # on 2026-08-29 -- but only in the GENERATED file.  Regenerating would
    # have silently undone the conversion at 88 places (85 keyword calls
    # plus kw_eq itself); measured 2026-09-04 by running the generator
    # against the checked-in state.
    # The Slice carries its length, so the `len` parameter is gone.
    out.append("; True when the scanned bytes equal the ASCII literal `word`.")
    out.append(";")
    out.append("; \u2605\u2605\u2605BOTH SIDES ARE A VIEW since 2026-09-05. `buf` was a bare")
    out.append("; `pointer[char]` whose length lived in the CALLER -- the shape")
    out.append("; of a chain: this body proved `buf` a")
    out.append("; buffer while its own signature carried no length, and")
    out.append("; get_identifier_token one level up carried the length while proving")
    out.append("; nothing. Neither could convert alone.")
    out.append(";")
    out.append("; \u2605The length test is not redundant even though every caller")
    out.append("; dispatches on length first: it is what lets the subscript's bounds")
    out.append("; check fold away, since the loop then runs against the SAME length the")
    out.append("; check reads. Without it the two lengths are unrelated to the optimizer.")
    out.append("function kw_eq(buf: Slice[char], word: Slice[char]) returns bool")
    out.append("{")
    out.append("    if buf.length <> word.length")
    out.append("        return false")
    out.append("    var i: int 0")
    out.append("    while i < word.length")
    out.append("    {")
    out.append("        if (buf[i] as int) <> (word[i] as int)")
    out.append("            return false")
    out.append("        i := i + 1")
    out.append("    }")
    out.append("    true")
    out.append("}")
    out.append("")
    out.append("; GetIdentifierToken — the Kind for an already-scanned identifier: its")
    out.append("; keyword Kind if it is one, KindIdentifier otherwise.")
    out.append("function get_identifier_token(buf: Slice[char]) returns int")
    out.append("{")
    out.append("    let len buf.length as int")
    out.append("    ; The reference's guard, ported verbatim.")
    out.append("    if len < %d" % lo)
    out.append("        return KindIdentifier")
    out.append("    if len > %d" % hi)
    out.append("        return KindIdentifier")
    out.append("    let c0 buf[0] as int")
    out.append('    if c0 < (("a" as char) as int)')
    out.append("        return KindIdentifier")
    out.append('    if c0 > (("z" as char) as int)')
    out.append("        return KindIdentifier")
    out.append("")

    for n in sorted(by_len):
        out.append("    if len = %d" % n)
        out.append("    {")
        for text, kind in sorted(by_len[n]):
            # ★★★THE LITERAL GOES STRAIGHT INTO THE SLICE PARAMETER, since the
            # compiler materialises it there (2026-09-05).  Before, the
            # hand-counted length stood here -- `Slice[char](%d, "%s")` -- and
            # that price per call site was why a pointer[const_char] parameter
            # did not seem worth it.  Same emission: the compiler builds the
            # same tuple.
            # ★The length it takes is the DECODED byte count.  For plain ASCII
            # identifiers that is n; the assertion stands here so that a keyword
            # with an escape does not silently miss.
            assert len(text) == n and text.isascii() and "\\" not in text, text
            out.append('        if kw_eq(buf, "%s")' % text)
            out.append("            return %s" % kind)
        out.append("    }")
        out.append("")

    out.append("    KindIdentifier")
    out.append("}")
    out.append("")

    # ── the viable keyword suggestions ──────────────────────────────────────
    #
    # GetViableKeywordSuggestions(): every key of textToKeyword longer than two
    # characters. The reference builds it by ranging over the MAP, so its order
    # is random — which is sound there because GetSpellingSuggestion's answer is
    # order-independent (minimum distance, ties broken lexicographically). It is
    # emitted sorted here so that the generated file is stable across runs.
    #
    # Two accessors rather than an array of Strings: a `define X: T[]` global is
    # a VALUE, not a pointer, and cannot be handed to a pointer parameter,
    # while a cstring literal per index costs nothing and is what
    # kw_eq already compares against.
    viable = sorted(t for t, _ in entries if len(t) > 2)
    out.append(
        "; The reference's GetViableKeywordSuggestions — every keyword longer"
    )
    out.append(
        "; than two characters, which is the candidate set"
    )
    out.append(
        "; parseErrorForMissingSemicolonAfter spell-checks an identifier against."
    )
    out.append(
        "; Sorted, which the reference's map range is not; the answer does not"
    )
    out.append("; depend on the order (see the generator).")
    out.append("define KEYWORD_SUGGESTION_COUNT: int %d" % len(viable))
    out.append("")
    out.append("function viable_keyword_suggestion(i: int) returns Slice[char]")
    out.append("{")
    for n, text in enumerate(viable):
        out.append("    if i = %d" % n)
        out.append('        return "%s"' % text)
    out.append('    ""')
    out.append("}")
    out.append("")
    out.append("function viable_keyword_suggestion_length(i: int) returns int")
    out.append("{")
    for n, text in enumerate(viable):
        out.append("    if i = %d" % n)
        out.append("        return %d" % len(text))
    out.append("    0")
    out.append("}")
    out.append("")
    return "\n".join(out)


def main():
    if not os.path.exists(SRC):
        sys.exit(
            "genkeywords: reference not found at\n  %s\n"
            "Initialize the submodule:\n"
            "  git submodule update --init packages/tscaly/_submodules/typescript-go"
            % SRC
        )

    entries = parse(SRC)
    with open(DST, "w", encoding="utf-8") as f:
        f.write(emit(entries))

    print(
        "genkeywords: %d keywords (%d suggestible) -> %s"
        % (
            len(entries),
            len([t for t, _ in entries if len(t) > 2]),
            os.path.relpath(DST, REPO),
        )
    )


if __name__ == "__main__":
    main()
