#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
#
# genmessages.py — generate tscaly/DiagnosticMessages.scaly: EVERY message of the
# pinned reference's internal/diagnostics/diagnostics_generated.go, its text and its
# category, by code.
#
# ★ WHY A SECOND TABLE BESIDE DiagnosticCodes.scaly. That one is the port's NAMES and
# is scoped to the sources that report (its header says why). The driver (phase (b)2)
# PRINTS messages — a diagnostic's text through diagnostics.Format, the help screen's
# descriptions and category headers, `Version 0` — and which message a program prints
# is decided at run time by whatever the checker reported, so the text table cannot be
# scoped to a list of sources. It is keyed by CODE, which is unique in the table (the
# generator refuses a duplicate rather than picking one).
#
# ★ The lookup is a two-level dispatch (the code's thousand, then the code), not an
# array: codes are sparse (1002 … 100010) and a Scaly const array holds bare integers.
#
# Usage (from the repo root, submodule initialized):
#   packages/tscaly/tools/genmessages.py

import os
import re
import sys

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
SUB = os.path.join(REPO, "packages/tscaly/_submodules/typescript-go")
TABLE = os.path.join(SUB, "internal/diagnostics/diagnostics_generated.go")
DST = os.path.join(REPO, "packages/tscaly/0.1.0/tscaly/DiagnosticMessages.scaly")

ENTRY = re.compile(r'^var (\w+) = &Message\{code: (\d+), category: Category(\w+), key: "([^"]*)", text: "((?:[^"\\]|\\.)*)"')
CATEGORIES = {"Warning": 0, "Error": 1, "Suggestion": 2, "Message": 3}


def scaly_literal(go_text):
    text = bytes(go_text, "utf-8").decode("unicode_escape").encode("latin-1").decode("utf-8")
    out = []
    for ch in text:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "`":
            out.append("\\`")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def main():
    if not os.path.exists(TABLE):
        sys.exit("the reference submodule is not initialized — nothing to generate from")
    rows = {}
    total = 0
    with open(TABLE, encoding="utf-8") as f:
        for line in f:
            if "&Message{" not in line:
                continue
            total += 1
            m = ENTRY.match(line)
            if not m:
                sys.exit("unparsable message line: " + line[:120])
            code = int(m.group(2))
            if code in rows:
                sys.exit("duplicate code %d" % code)
            rows[code] = (CATEGORIES[m.group(3)], scaly_literal(m.group(5)), m.group(4), "reportsUnnecessary: true" in line, "reportsDeprecated: true" in line)
    if len(rows) != total:
        sys.exit("parsed %d of %d messages" % (len(rows), total))

    w = []
    p = w.append
    p("; SPDX-License-Identifier: Apache-2.0")
    p(";")
    p("; DiagnosticMessages — every message's text and category by code, ported from the")
    p("; reference's internal/diagnostics/diagnostics_generated.go.")
    p(";")
    p("; GENERATED by packages/tscaly/tools/genmessages.py. Do not edit; edit the")
    p("; generator. Regenerate after a submodule pin bump.")
    p(";")
    p("; %d messages." % len(rows))
    p("")
    p("define DiagnosticCategoryWarning: int 0")
    p("define DiagnosticCategoryError: int 1")
    p("define DiagnosticCategorySuggestion: int 2")
    p("define DiagnosticCategoryMessage: int 3")
    p("")
    p("define DiagnosticMessages")
    p("{")
    groups = {}
    for code in sorted(rows):
        groups.setdefault(code // 1000, []).append(code)
    p("    ; the message text (before diagnostics.Format), empty for a code the table lacks")
    p("    function text_of(code: int) returns Slice[char]")
    p("    {")
    p("        let group code / 1000")
    for g in sorted(groups):
        p("        if group = %d" % g)
        p("            return DiagnosticMessages.text_of_%d(code)" % g)
    p('        ""')
    p("    }")
    p("")
    p("    ; the category (DiagnosticCategory*), Error for a code the table lacks")
    p("    function category_of(code: int) returns int")
    p("    {")
    p("        let group code / 1000")
    for g in sorted(groups):
        p("        if group = %d" % g)
        p("            return DiagnosticMessages.category_of_%d(code)" % g)
    p("        DiagnosticCategoryError")
    p("    }")
    p("")
    p("    ; the message key (diagnostics.Key), empty for a code the table lacks")
    p("    function key_of(code: int) returns Slice[char]")
    p("    {")
    p("        let group code / 1000")
    for g in sorted(groups):
        p("        if group = %d" % g)
        p("            return DiagnosticMessages.key_of_%d(code)" % g)
    p('        ""')
    p("    }")
    p("")
    p("    ; Message.ReportsUnnecessary")
    p("    function reports_unnecessary(code: int) returns bool")
    p("    {")
    for code in sorted(rows):
        if rows[code][3]:
            p("        if code = %d" % code)
            p("            return true")
    p("        false")
    p("    }")
    p("")
    p("    ; Message.ReportsDeprecated")
    p("    function reports_deprecated(code: int) returns bool")
    p("    {")
    for code in sorted(rows):
        if rows[code][4]:
            p("        if code = %d" % code)
            p("            return true")
    p("        false")
    p("    }")
    for g in sorted(groups):
        p("")
        p("    function key_of_%d(code: int) returns Slice[char]" % g)
        p("    {")
        for code in groups[g]:
            p("        if code = %d" % code)
            p('            return "%s"' % rows[code][2])
        p('        ""')
        p("    }")
    for g in sorted(groups):
        p("")
        p("    function text_of_%d(code: int) returns Slice[char]" % g)
        p("    {")
        for code in groups[g]:
            p("        if code = %d" % code)
            p("            return %s" % rows[code][1])
        p('        ""')
        p("    }")
        p("")
        p("    function category_of_%d(code: int) returns int" % g)
        p("    {")
        for code in groups[g]:
            if rows[code][0] != 1:
                p("        if code = %d" % code)
                p("            return %d" % rows[code][0])
        p("        DiagnosticCategoryError")
        p("    }")
    p("}")
    with open(DST, "w", encoding="utf-8") as fh:
        fh.write("\n".join(w) + "\n")
    print("%s: %d messages in %d groups" % (DST, len(rows), len(groups)))


if __name__ == "__main__":
    main()
